start.compose:
	cd deployments && docker compose up --build

compose.up:
	cd deployments && docker compose up

start.db:
	cd deployments && docker compose db -d

start.app:
	cd deployments && docker compose app -d

start.web-server:
	cd deployments && docker compose web-server -d

down:
	cd deployments && docker compose down
