version: '3'

services:
  app:
    hostname: mireabackend.dev
    container_name: myapp
    build:
      context: ../
      dockerfile: ./deployments/Dockerfile.app
      target: prod
    environment:
      - SHELL_PATH=/bin/sh

  web-server:
    image: nginx
    container_name: myapp-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./hosts:/etc/nginx/conf.d
    depends_on:
      - app
