version: '3'

services:
  app:
    hostname: mireabackend.dev
    container_name: myapp
    build:
      context: ../
      dockerfile: ./deployments/Dockerfile.app
      target: prod
    environment:
      - DB_URL=postgres://postgres:mydbpassword@dockerdev.db:5432/postgres?sslmode=disable&
      - FILE_DB_URL=mongodb://root:mysecretpassword@mongo.dev:27017/mydb?ssl=false&authSource=admin
      - REDIS_URL=redis://:mysecretpassword@redis.dev:6379/0
    depends_on:
      - db
      - mongo

  db:
    hostname: dockerdev.db
    build:
      dockerfile: ./deployments/Dockerfile.postgresql
      context: ../
    environment:
      - POSTGRES_PASSWORD=mydbpassword
    container_name: myapp-db
    ports:
      - "5432:5432"
  
  mongo:
    hostname: mongo.dev
    image: mongo
    container_name: mongo-db
    environment:
      - MONGO_INITDB_DATABASE=mydb
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mysecretpassword
    ports:
      - "27017:27017"
  
  redis:
    hostname: redis.dev
    image: redis:7.0.5
    container_name: redisdb
    command: redis-server --requirepass mysecretpassword
    ports:
      - "6379:6379"

  web-server:
    image: nginx
    container_name: myapp-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ../web:/web
    depends_on:
      - app
